# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataAcquireWin.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dataAcquireWin(object):
    def setupUi(self, dataAcquireWin):
        dataAcquireWin.setObjectName(_fromUtf8("dataAcquireWin"))
        dataAcquireWin.resize(1031, 634)
        dataAcquireWin.setMinimumSize(QtCore.QSize(1031, 634))
        dataAcquireWin.setMaximumSize(QtCore.QSize(1031, 634))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        dataAcquireWin.setFont(font)
        dataAcquireWin.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.centralwidget = QtGui.QWidget(dataAcquireWin)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 1031, 16))
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 1011, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(0, 0, 91);"))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 190, 1031, 16))
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 320, 1031, 16))
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 340, 371, 261))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.actionShowLabel = QtGui.QLabel(self.groupBox)
        self.actionShowLabel.setGeometry(QtCore.QRect(120, 0, 211, 101))
        self.actionShowLabel.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 255);\n"
"border-color: rgb(0, 0, 0);"))
        self.actionShowLabel.setText(_fromUtf8(""))
        # self.actionShowLabel.setPixmap(QtGui.QPixmap(_fromUtf8("src/u=1737923256,435503271&fm=200&gp=0.jpg")))
        self.actionShowLabel.setScaledContents(True)
        self.actionShowLabel.setObjectName(_fromUtf8("actionShowLabel"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 100, 321, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_3.addWidget(self.label_18)
        self.dataAcquireProgressBar = QtGui.QProgressBar(self.layoutWidget)
        self.dataAcquireProgressBar.setProperty("value", 10)
        self.dataAcquireProgressBar.setObjectName(_fromUtf8("dataAcquireProgressBar"))
        self.horizontalLayout_3.addWidget(self.dataAcquireProgressBar)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 180, 331, 51))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.startAcquireDataPushBt = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.startAcquireDataPushBt.setFont(font)
        self.startAcquireDataPushBt.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.startAcquireDataPushBt.setObjectName(_fromUtf8("startAcquireDataPushBt"))
        self.horizontalLayout_4.addWidget(self.startAcquireDataPushBt)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.stopAcquireDataPushBt = QtGui.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.stopAcquireDataPushBt.setFont(font)
        self.stopAcquireDataPushBt.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.stopAcquireDataPushBt.setObjectName(_fromUtf8("stopAcquireDataPushBt"))
        self.horizontalLayout_4.addWidget(self.stopAcquireDataPushBt)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(350, 330, 301, 251))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 140, 281, 41))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_23 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_7.addWidget(self.label_23)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.parameterSelectCheckBox = QtGui.QCheckBox(self.layoutWidget2)
        self.parameterSelectCheckBox.setMinimumSize(QtCore.QSize(0, 0))
        self.parameterSelectCheckBox.setText(_fromUtf8(""))
        self.parameterSelectCheckBox.setTristate(False)
        self.parameterSelectCheckBox.setObjectName(_fromUtf8("parameterSelectCheckBox"))
        self.horizontalLayout_7.addWidget(self.parameterSelectCheckBox)
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 190, 281, 51))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.startTrainMOdelPushBt = QtGui.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.startTrainMOdelPushBt.setFont(font)
        self.startTrainMOdelPushBt.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.startTrainMOdelPushBt.setObjectName(_fromUtf8("startTrainMOdelPushBt"))
        self.horizontalLayout_6.addWidget(self.startTrainMOdelPushBt)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.stopTrainModelPushBt = QtGui.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.stopTrainModelPushBt.setFont(font)
        self.stopTrainModelPushBt.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.stopTrainModelPushBt.setObjectName(_fromUtf8("stopTrainModelPushBt"))
        self.horizontalLayout_6.addWidget(self.stopTrainModelPushBt)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 40, 281, 51))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_21 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_5.addWidget(self.label_21)
        self.modelSelectComboBox = QtGui.QComboBox(self.layoutWidget3)
        self.modelSelectComboBox.setMinimumSize(QtCore.QSize(100, 30))
        self.modelSelectComboBox.setObjectName(_fromUtf8("modelSelectComboBox"))
        self.modelSelectComboBox.addItem(_fromUtf8(""))
        self.modelSelectComboBox.addItem(_fromUtf8(""))
        self.modelSelectComboBox.addItem(_fromUtf8(""))
        self.modelSelectComboBox.addItem(_fromUtf8(""))
        self.modelSelectComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.modelSelectComboBox)
        self.layoutWidget4 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 90, 281, 51))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_22 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_8.addWidget(self.label_22)
        self.featureSelectComboBox = QtGui.QComboBox(self.layoutWidget4)
        self.featureSelectComboBox.setMinimumSize(QtCore.QSize(100, 30))
        self.featureSelectComboBox.setObjectName(_fromUtf8("featureSelectComboBox"))
        self.featureSelectComboBox.addItem(_fromUtf8(""))
        self.featureSelectComboBox.addItem(_fromUtf8(""))
        self.featureSelectComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.featureSelectComboBox)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(330, 330, 20, 251))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.layoutWidget5 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 80, 1011, 101))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.label_6 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.label_2 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.nameLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.horizontalLayout.addWidget(self.nameLineEdit)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.label_7 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.label_3 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.ageLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.ageLineEdit.setObjectName(_fromUtf8("ageLineEdit"))
        self.horizontalLayout.addWidget(self.ageLineEdit)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.label_8 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.label_4 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.sexComboBox = QtGui.QComboBox(self.layoutWidget5)
        self.sexComboBox.setMinimumSize(QtCore.QSize(120, 30))
        self.sexComboBox.setObjectName(_fromUtf8("sexComboBox"))
        self.sexComboBox.addItem(_fromUtf8(""))
        self.sexComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.sexComboBox)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.label_9 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.label_5 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.badSideComboBox = QtGui.QComboBox(self.layoutWidget5)
        self.badSideComboBox.setMinimumSize(QtCore.QSize(120, 30))
        self.badSideComboBox.setObjectName(_fromUtf8("badSideComboBox"))
        self.badSideComboBox.addItem(_fromUtf8(""))
        self.badSideComboBox.addItem(_fromUtf8(""))
        self.badSideComboBox.addItem(_fromUtf8(""))
        self.badSideComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.badSideComboBox)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.layoutWidget6 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 210, 1011, 111))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.label_15 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_2.addWidget(self.label_15)
        self.label_10 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.actionTimeSpinBox = QtGui.QSpinBox(self.layoutWidget6)
        self.actionTimeSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionTimeSpinBox.setFont(font)
        self.actionTimeSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.actionTimeSpinBox.setMaximum(20)
        self.actionTimeSpinBox.setProperty("value", 8)
        self.actionTimeSpinBox.setObjectName(_fromUtf8("actionTimeSpinBox"))
        self.horizontalLayout_2.addWidget(self.actionTimeSpinBox)
        self.label_13 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_2.addWidget(self.label_13)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.label_16 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_2.addWidget(self.label_16)
        self.label_11 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.restTimeSpinBox = QtGui.QSpinBox(self.layoutWidget6)
        self.restTimeSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.restTimeSpinBox.setFont(font)
        self.restTimeSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.restTimeSpinBox.setMaximum(20)
        self.restTimeSpinBox.setProperty("value", 6)
        self.restTimeSpinBox.setObjectName(_fromUtf8("restTimeSpinBox"))
        self.horizontalLayout_2.addWidget(self.restTimeSpinBox)
        self.label_14 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_2.addWidget(self.label_14)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.label_17 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_2.addWidget(self.label_17)
        self.label_12 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_2.addWidget(self.label_12)
        self.actionSelectComboBox = QtGui.QComboBox(self.layoutWidget6)
        self.actionSelectComboBox.setMinimumSize(QtCore.QSize(100, 30))
        self.actionSelectComboBox.setObjectName(_fromUtf8("actionSelectComboBox"))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.actionSelectComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.actionSelectComboBox)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.actionShowTextBrowser = QtGui.QTextBrowser(self.layoutWidget6)
        self.actionShowTextBrowser.setMaximumSize(QtCore.QSize(200, 150))
        self.actionShowTextBrowser.setObjectName(_fromUtf8("actionShowTextBrowser"))
        self.horizontalLayout_2.addWidget(self.actionShowTextBrowser)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 580, 1031, 16))
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.showSignalPushBt = QtGui.QPushButton(self.centralwidget)
        self.showSignalPushBt.setGeometry(QtCore.QRect(920, 420, 101, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.showSignalPushBt.setFont(font)
        self.showSignalPushBt.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 85, 0);"))
        self.showSignalPushBt.setObjectName(_fromUtf8("showSignalPushBt"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(650, 330, 20, 251))
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(670, 330, 231, 241))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.groupBox_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.testActionShowLabel = QtGui.QLabel(self.groupBox_6)
        self.testActionShowLabel.setGeometry(QtCore.QRect(10, 40, 211, 131))
        self.testActionShowLabel.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 255);\n"
"border-color: rgb(0, 0, 0);"))
        self.testActionShowLabel.setText(_fromUtf8(""))
        # self.testActionShowLabel.setPixmap(QtGui.QPixmap(_fromUtf8("src/u=1060469999,2807571099&fm=200&gp=0.jpg")))
        self.testActionShowLabel.setScaledContents(True)
        self.testActionShowLabel.setObjectName(_fromUtf8("testActionShowLabel"))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 190, 211, 51))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.startTestPushBt = QtGui.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.startTestPushBt.setFont(font)
        self.startTestPushBt.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.startTestPushBt.setObjectName(_fromUtf8("startTestPushBt"))
        self.horizontalLayout_14.addWidget(self.startTestPushBt)
        self.stopTestPushBt = QtGui.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AR PL UKai TW"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.stopTestPushBt.setFont(font)
        self.stopTestPushBt.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.stopTestPushBt.setObjectName(_fromUtf8("stopTestPushBt"))
        self.horizontalLayout_14.addWidget(self.stopTestPushBt)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(900, 330, 20, 251))
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        dataAcquireWin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(dataAcquireWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        dataAcquireWin.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(dataAcquireWin)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        dataAcquireWin.setStatusBar(self.statusbar)

        self.retranslateUi(dataAcquireWin)
        QtCore.QMetaObject.connectSlotsByName(dataAcquireWin)

    def retranslateUi(self, dataAcquireWin):
        dataAcquireWin.setWindowTitle(_translate("dataAcquireWin", "emgDataAcquire", None))
        self.label.setText(_translate("dataAcquireWin", "欢迎使用表面肌电信号采集系统", None))
        self.groupBox.setTitle(_translate("dataAcquireWin", "数据采集", None))
        self.label_18.setText(_translate("dataAcquireWin", "状态显示：", None))
        self.startAcquireDataPushBt.setText(_translate("dataAcquireWin", "开始采集", None))
        self.stopAcquireDataPushBt.setText(_translate("dataAcquireWin", "停止采集", None))
        self.groupBox_2.setTitle(_translate("dataAcquireWin", "模型训练", None))
        self.label_23.setText(_translate("dataAcquireWin", "滑动窗参数选择：", None))
        self.startTrainMOdelPushBt.setText(_translate("dataAcquireWin", "开始训练", None))
        self.stopTrainModelPushBt.setText(_translate("dataAcquireWin", "停止训练", None))
        self.label_21.setText(_translate("dataAcquireWin", "模型选择：", None))
        self.modelSelectComboBox.setItemText(0, _translate("dataAcquireWin", "LDA", None))
        self.modelSelectComboBox.setItemText(1, _translate("dataAcquireWin", "SVM", None))
        self.modelSelectComboBox.setItemText(2, _translate("dataAcquireWin", "KNN", None))
        self.modelSelectComboBox.setItemText(3, _translate("dataAcquireWin", "DNN", None))
        self.modelSelectComboBox.setItemText(4, _translate("dataAcquireWin", "XGBOOST", None))
        self.label_22.setText(_translate("dataAcquireWin", "特征选择：", None))
        self.featureSelectComboBox.setItemText(0, _translate("dataAcquireWin", "MAV", None))
        self.featureSelectComboBox.setItemText(1, _translate("dataAcquireWin", "ZC", None))
        self.featureSelectComboBox.setItemText(2, _translate("dataAcquireWin", "WL", None))
        self.label_6.setText(_translate("dataAcquireWin", "*", None))
        self.label_2.setText(_translate("dataAcquireWin", "姓名：", None))
        self.label_7.setText(_translate("dataAcquireWin", "*", None))
        self.label_3.setText(_translate("dataAcquireWin", "年龄：", None))
        self.label_8.setText(_translate("dataAcquireWin", "*", None))
        self.label_4.setText(_translate("dataAcquireWin", "性别：", None))
        self.sexComboBox.setItemText(0, _translate("dataAcquireWin", "男", None))
        self.sexComboBox.setItemText(1, _translate("dataAcquireWin", "女", None))
        self.label_9.setText(_translate("dataAcquireWin", "*", None))
        self.label_5.setText(_translate("dataAcquireWin", "患侧：", None))
        self.badSideComboBox.setItemText(0, _translate("dataAcquireWin", "左侧", None))
        self.badSideComboBox.setItemText(1, _translate("dataAcquireWin", "右侧", None))
        self.badSideComboBox.setItemText(2, _translate("dataAcquireWin", "双侧", None))
        self.badSideComboBox.setItemText(3, _translate("dataAcquireWin", "无", None))
        self.label_15.setText(_translate("dataAcquireWin", "*", None))
        self.label_10.setText(_translate("dataAcquireWin", "动作时间：", None))
        self.label_13.setText(_translate("dataAcquireWin", "min", None))
        self.label_16.setText(_translate("dataAcquireWin", "*", None))
        self.label_11.setText(_translate("dataAcquireWin", "休息时间：", None))
        self.label_14.setText(_translate("dataAcquireWin", "min", None))
        self.label_17.setText(_translate("dataAcquireWin", "*", None))
        self.label_12.setText(_translate("dataAcquireWin", "动作选择：", None))
        self.actionSelectComboBox.setItemText(0, _translate("dataAcquireWin", "fist", None))
        self.actionSelectComboBox.setItemText(1, _translate("dataAcquireWin", "openHand", None))
        self.actionSelectComboBox.setItemText(2, _translate("dataAcquireWin", "one", None))
        self.actionSelectComboBox.setItemText(3, _translate("dataAcquireWin", "two", None))
        self.actionSelectComboBox.setItemText(4, _translate("dataAcquireWin", "three", None))
        self.actionSelectComboBox.setItemText(5, _translate("dataAcquireWin", "four", None))
        self.actionSelectComboBox.setItemText(6, _translate("dataAcquireWin", "five", None))
        self.actionSelectComboBox.setItemText(7, _translate("dataAcquireWin", "six", None))
        self.actionSelectComboBox.setItemText(8, _translate("dataAcquireWin", "love", None))
        self.actionSelectComboBox.setItemText(9, _translate("dataAcquireWin", "good", None))
        self.actionSelectComboBox.setItemText(10, _translate("dataAcquireWin", "low", None))
        self.actionSelectComboBox.setItemText(11, _translate("dataAcquireWin", "boom", None))
        self.showSignalPushBt.setText(_translate("dataAcquireWin", "显示波形", None))
        self.groupBox_6.setTitle(_translate("dataAcquireWin", "在线分类测试", None))
        self.startTestPushBt.setText(_translate("dataAcquireWin", "开始", None))
        self.stopTestPushBt.setText(_translate("dataAcquireWin", "结束", None))

# import pic_rc
